import { createElement, type ComponentProps } from "react";
import {
  Shield,
  Leaf,
  BookOpen,
  Search,
  TrendingUp,
  Users,
  Cpu,
  FlaskConical,
  Star,
  Zap,
  Globe,
  Target,
  Award,
  BarChart2,
  Brain,
  Layers,
  Settings,
  Database,
  Code,
  Heart,
  Building2,
  Briefcase,
  ChartBar,
  GraduationCap,
  FileText,
  Scale,
  Microscope,
  TreePine,
  Landmark,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  Shield,
  Leaf,
  BookOpen,
  Search,
  TrendingUp,
  Users,
  Cpu,
  FlaskConical,
  Star,
  Zap,
  Globe,
  Target,
  Award,
  BarChart2,
  Brain,
  Layers,
  Settings,
  Database,
  Code,
  Heart,
  Building2,
  Briefcase,
  ChartBar,
  GraduationCap,
  FileText,
  Scale,
  Microscope,
  TreePine,
  Landmark,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? Shield;
}

export function renderIcon(name: string, props: ComponentProps<LucideIcon>) {
  return createElement(getIcon(name), props);
}

export const iconOptions: { name: string; label: string }[] = [
  { name: "Shield", label: "Shield" },
  { name: "Leaf", label: "Leaf" },
  { name: "BookOpen", label: "BookOpen" },
  { name: "Search", label: "Search" },
  { name: "TrendingUp", label: "TrendingUp" },
  { name: "Users", label: "Users" },
  { name: "Cpu", label: "Cpu" },
  { name: "FlaskConical", label: "FlaskConical" },
  { name: "Star", label: "Star" },
  { name: "Zap", label: "Zap" },
  { name: "Globe", label: "Globe" },
  { name: "Target", label: "Target" },
  { name: "Award", label: "Award" },
  { name: "BarChart2", label: "BarChart2" },
  { name: "Brain", label: "Brain" },
  { name: "Layers", label: "Layers" },
  { name: "Settings", label: "Settings" },
  { name: "Database", label: "Database" },
  { name: "Code", label: "Code" },
  { name: "Heart", label: "Heart" },
  { name: "Building2", label: "Building2" },
  { name: "Briefcase", label: "Briefcase" },
  { name: "GraduationCap", label: "GraduationCap" },
  { name: "FileText", label: "FileText" },
  { name: "Scale", label: "Scale" },
  { name: "Microscope", label: "Microscope" },
  { name: "TreePine", label: "TreePine" },
  { name: "Landmark", label: "Landmark" },
];
